### ISSUE TITLE
[Error] I try create a bat file

### ISSUE THREAD

**Issue by Neinndall** [autergame/BinReader-Rust#1]
binreader-rust_windows.exe *.bin *.json

```
thread 'main' panicked at 'Could not open file: Os { code: 123, kind: InvalidFilename, message: "The filename, directory name, or volume label syntax is not correct." }', src\main.rs:157:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by fernpi** [comment]
Currently it doesn't work with multiple bins

**Comment by Neinndall** [comment]
I am not trying to convert several bins, but only one, but I would like the program to detect the *.bin file in the directory.

**Comment by fernpi** [comment]
Added: https://github.com/autergame/BinReader-Rust/releases/tag/v0.2.0
